
[build-system]
requires = ["wheel", "setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
include = ".*pyi?$"
target-version = ["py38"]


[tool.isort]
profile = "black"
force_single_line = true

